import type { Database, DatabaseDescriptor } from "emdash";
import { kyselyLogOption } from "emdash/database/instrumentation";
import { Kysely } from "kysely";
// @ts-ignore -- generated by the EmDash Astro integration at build time
import virtualConfig from "virtual:emdash/config";
// @ts-ignore -- generated by the EmDash Astro integration at build time
import * as dialect from "virtual:emdash/dialect";

const DUMMY_URL = new URL("http://localhost");

interface DummyCookieJar {
	get(): { value: string } | undefined;
	set(): void;
}

const dummyCookies: DummyCookieJar = {
	get: () => undefined,
	set: () => {},
};

interface RequestScopedDb {
	db: Kysely<unknown>;
	commit(): void;
	close?(): void;
}

export interface WithBridgeDbOptions {
	isWrite?: boolean;
}

function getDatabaseDescriptor(): DatabaseDescriptor {
	const descriptor = (virtualConfig as Record<string, unknown> | undefined)?.database as
		| DatabaseDescriptor
		| undefined;

	if (!descriptor) {
		throw new Error(
			"No EmDash database adapter is configured. Sandboxed plugins cannot access the database.",
		);
	}

	return descriptor;
}

function openScopedDb(descriptor: DatabaseDescriptor, isWrite: boolean): RequestScopedDb {
	if (typeof dialect.createRequestScopedDb !== "function") {
		throw new Error(
			"The configured database adapter does not expose createRequestScopedDb. " +
				"Sandboxed plugins require an adapter that supports event-scoped connections.",
		);
	}

	const scoped = dialect.createRequestScopedDb({
		config: descriptor.config,
		isAuthenticated: false,
		isWrite,
		url: DUMMY_URL,
		cookies: dummyCookies,
		canUseCachedBinding: false,
		// eslint-disable-next-line typescript-eslint/no-unsafe-type-assertion -- adapter-specific opts are deliberately opaque to the bridge
	} as never);

	if (!scoped) {
		throw new Error(
			"The configured database adapter returned a null event-scoped database for the sandbox bridge. " +
				"Connection-backed adapters must provide one.",
		);
	}

	return scoped as RequestScopedDb;
}

function openSingletonDb(descriptor: DatabaseDescriptor): Kysely<Database> {
	if (typeof dialect.createDialect !== "function") {
		throw new Error(
			"The configured database adapter does not expose createDialect. " +
				"Sandboxed plugins require a database adapter.",
		);
	}

	return new Kysely<Database>({
		// eslint-disable-next-line typescript-eslint/no-unsafe-type-assertion -- adapter-specific config is deliberately opaque to the bridge
		dialect: dialect.createDialect(descriptor.config as never),
		log: kyselyLogOption(),
	});
}

/**
 * Run a callback against an event-scoped database connection.
 *
 * For connection-backed adapters (e.g. Hyperdrive), this opens a fresh
 * connection per bridge request/event and closes it afterwards, so sockets
 * are never reused across events. Stateful adapters (D1, DO SQL) fall back
 * to the runtime singleton when they do not return a per-event DB.
 */
export async function withBridgeDb<T>(
	options: WithBridgeDbOptions,
	fn: (db: Kysely<Database>) => Promise<T>,
): Promise<T> {
	const descriptor = getDatabaseDescriptor();
	const isWrite = options.isWrite ?? true;

	let scoped: RequestScopedDb | undefined;
	let db: Kysely<Database>;
	let shouldClose = false;

	try {
		scoped = openScopedDb(descriptor, isWrite);
		db = scoped.db as Kysely<Database>;
		shouldClose = true;
	} catch {
		db = openSingletonDb(descriptor);
	}

	try {
		return await fn(db);
	} finally {
		if (scoped) {
			scoped.commit();
			if (shouldClose && typeof scoped.close === "function") {
				try {
					scoped.close();
				} catch (error) {
					console.error("[plugin-bridge] failed to close event-scoped db:", error);
				}
			}
		}
	}
}
